language: python
python:
  - "3.9"
  
before_install:
  - echo "Nothing before install"

  
install:
  - pip install -r requirements.txt

script:
  - pip uninstall -y urllib3
  - pip install urllib3==1.26.7
  - echo "Running tests"
  - python -m pytest -v

after_success:
  - echo "Finished running tests"
