name: Deploy App to Code Engine

on:
  push:
    branches:
      - deploy
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Podman
        run: |
              sudo apt-get update
              sudo apt-get install -y podman
      - name: Run Podman command
        run: |
              podman build --platform=linux/amd64 . -t responsible-prompting-api:v0
              
  deploy-app:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Deploy Application to Code Engine
      uses: IBM/code-engine-github-action@v1
      with:
        api-key: ${{ secrets.IBM_IAM_API_KEY }}
        resource-group: 'brl-all'
        region: 'us-south'
        project: 'brl-all'
        component: 'app'
        name: 'responsible-prompting-deploy'
        build-source: './'
        # cpu: 1
        # memory: 8G
        # ephemeral-storage: 4.4
